---
title: "Homework 5"
author: "Sarah McLarnan"
date: 2019-11-04
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_bw() + theme(legend.position = "bottom"))
```

### Problem 1

```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

```{r}
clean_iris = function(x) {
  
   if (is.numeric(x)) {
   replace_na(x, mean(x, na.rm = TRUE))
   }
   else if (is.character(x)) 
     {replace_na(x, "virginica")}
}

output = map_dfr(.x = iris_with_missing, ~ clean_iris(.x))
output %>%
  view()
```

### Problem 2

```{r}
names_df =
  tibble(
  subject = list.files(path="./data")
)
file_path = "./data/"
file_names = file_path %>%
  list.files()
observations_df =
  file_names %>%
  map_dfr(function(file_name){
 
  read_csv(paste0(file_path, file_name))
})
study_data = cbind(names_df, observations_df) %>%
 mutate(subject = str_replace(subject, ".csv", "")) %>%
 pivot_longer(
    week_1:week_8,
    names_to = "week",
    names_prefix = "week_",
    values_to = "observations")
study_data %>%
  ggplot(aes(x = as.numeric(week), y = observations, color = subject)) +
  geom_line() +
  labs(title = "Weekly observations by subject", x = "Week", y = "Observation Value") + theme(legend.position = "bottom")
```

### Problem 3

```{r}
sim_regression = function(n = 30, beta0 = 2, beta1 = 0) {
  
  sim_data = tibble(
    x = rnorm(n, mean = 1, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, 50)
  )
  
  ls_fit = lm(y ~ x, data = sim_data) %>%
     broom::tidy() %>%
     select(term, estimate, p.value)
  
}
sim_results = 
  tibble(beta1 = 0:6) %>% 
  mutate(
    output_lists = purrr::map(.x = beta1, ~rerun(10000, sim_regression(beta1 = .x))),
    estimate_dfs = purrr::map(output_lists, bind_rows)) %>% 
  select(-output_lists) %>% 
  unnest(estimate_dfs)
```